// Copyright 2025 Terramate GmbH
// SPDX-License-Identifier: MPL-2.0

stack {
  name        = "package resources // import \"github.com/terramate-io/terramate/cloud/api/resources\""
  description = "package resources // import \"github.com/terramate-io/terramate/cloud/api/resources\"\n\nPackage resources contains the resource entities used in the Terramate Cloud\nAPI.\n\ntype Author struct{ ... }\ntype BitbucketMetadata struct{ ... }\ntype ChangesetDetails struct{ ... }\ntype CommandLog struct{ ... }\ntype CommandLogs []*CommandLog\ntype CreatePreviewPayloadRequest struct{ ... }\ntype CreatePreviewResponse struct{ ... }\ntype DeploymentMetadata struct{ ... }\ntype DeploymentStackRequest struct{ ... }\ntype DeploymentStackRequests []DeploymentStackRequest\ntype DeploymentStackResponse struct{ ... }\ntype DeploymentStacksPayloadRequest struct{ ... }\ntype DeploymentStacksResponse []DeploymentStackResponse\ntype Drift struct{ ... }\ntype DriftStackPayloadRequest struct{ ... }\ntype DriftStackPayloadRequests []DriftStackPayloadRequest\ntype Drifts []Drift\ntype DriftsStackPayloadResponse struct{ ... }\ntype EmptyResponse string\ntype GitMetadata struct{ ... }\ntype GithubMetadata struct{ ... }\ntype GitlabMetadata struct{ ... }\ntype Label struct{ ... }\ntype LogChannel int\n    const StdoutLogChannel LogChannel ...\ntype MemberOrganization struct{ ... }\ntype MemberOrganizations []MemberOrganization\ntype PaginatedResult struct{ ... }\ntype PreviewStack struct{ ... }\ntype PreviewStacks []PreviewStack\ntype Resource interface{ ... }\ntype ResponsePreviewStack struct{ ... }\ntype ResponsePreviewStacks []ResponsePreviewStack\ntype ReviewRequest struct{ ... }\ntype ReviewRequestResponse struct{ ... }\ntype ReviewRequestResponsePayload struct{ ... }\ntype ReviewRequestResponses []ReviewRequestResponse\ntype Reviewer Author\ntype Reviewers []Reviewer\ntype SingleSignOnDetailResponse struct{ ... }\ntype Stack struct{ ... }\ntype StackObject struct{ ... }\ntype StacksResponse struct{ ... }\ntype StatusFilters struct{ ... }\n    func NoStatusFilters() StatusFilters\ntype StoreOutput struct{ ... }\ntype StoreOutputKey struct{ ... }\ntype StoreOutputRequest struct{ ... }\ntype UUID string\ntype UpdateDeploymentStack struct{ ... }\ntype UpdateDeploymentStacks struct{ ... }\ntype UpdateStackPreviewPayloadRequest struct{ ... }\ntype User struct{ ... }\ntype WellKnown struct{ ... }"
  tags        = ["api", "cloud", "golang", "resources"]
  id          = "2c422ea6-3ace-419e-8084-c4e96f59f627"
}
