# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

linters:
  enable:
    - revive
    - misspell
    - gofmt
issues:
  # So we can detect exported/undocumented symbols
  # https://github.com/golangci/golangci-lint/issues/2114
  exclude:
    - EXC0012
  exclude-use-default: false
