# Copyright 2023 Terramate GmbH
# SPDX-License-Identifier: MPL-2.0

linters:
  enable:
    - revive
    - misspell
    - gofmt
    - bodyclose
    - exportloopref
issues:
  # So we can detect exported/undocumented symbols
  # https://github.com/golangci/golangci-lint/issues/2114
  exclude:
    - EXC0012
  exclude-use-default: false

run:
  timeout: 15m
