linters:
  enable:
    - revive
    - misspell
    - gofmt
issues:
  # So we can detect exported/undocumented symbols
  # https://github.com/golangci/golangci-lint/issues/2114
  exclude:
    - EXC0012
  exclude-use-default: false
