# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

builds:
  - main: ./cmd/terramate
    env:
      - CGO_ENABLED=0
    ldflags:
      - -extldflags "-static"
    goos:
      - linux
      - darwin
      - windows
archives:
  -
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}

    format_overrides:
      - goos: windows
        format: zip

dockers:
  - dockerfile: hack/release/Dockerfile
    image_templates:
      - "ghcr.io/mineiros-io/{{.ProjectName}}:latest"
      - "ghcr.io/mineiros-io/{{.ProjectName}}:{{.Version}}"

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^spec:'
      - '^test:'
      - '^tests:'
      - '^testing:'
      - '^refactor:'
      - '^chore:'

announce:
  twitter:
    enabled: false
    message_template: |
      🥳 We just released #Terramate {{.Tag}} 🚀🚀🚀
      {{ .ReleaseURL }}

  slack:
    enabled: true
    message_template: |
      🥳 We just released #Terramate {{.Tag}} 🚀🚀🚀
      {{ .ReleaseURL }}

    channel: '#terramate'
    username: 'terramate'
    icon_emoji: ':terramate-logo:'

  discord:
    enabled: true

    message_template: |
      🥳 We just released #Terramate {{.Tag}} 🚀🚀🚀
      {{ .ReleaseURL }}

    author: 'terramate'

    # Default: 'https://goreleaser.com/static/avatar.png'
    icon_url: ''
