# Copyright 2022 Mineiros GmbH
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

builds:
  - main: ./cmd/terramate
    env:
      - CGO_ENABLED=0
    ldflags:
      - -extldflags "-static"
    goos:
      - linux
      - darwin
      - windows
archives:
  -
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}

    format_overrides:
      - goos: windows
        format: zip

dockers:
  - dockerfile: hack/release/Dockerfile
    image_templates:
      - "ghcr.io/mineiros-io/{{.ProjectName}}:latest"
      - "ghcr.io/mineiros-io/{{.ProjectName}}:{{.Version}}"

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^spec:'
      - '^test:'
      - '^tests:'
      - '^testing:'
      - '^refactor:'
      - '^chore:'

announce:
  twitter:
    enabled: false
    message_template: |
      🥳 We just released #Terramate {{.Tag}} 🚀🚀🚀
      {{ .ReleaseURL }}

  slack:
    enabled: true
    message_template: |
      🥳 We just released #Terramate {{.Tag}} 🚀🚀🚀
      {{ .ReleaseURL }}

    channel: '#terramate'
    username: 'terramate'
    icon_emoji: ':terramate-logo:'

  discord:
    enabled: true

    message_template: |
      🥳 We just released #Terramate {{.Tag}} 🚀🚀🚀
      {{ .ReleaseURL }}

    author: 'terramate'

    # Default: 'https://goreleaser.com/static/avatar.png'
    icon_url: ''
