# Copyright 2023 Terramate GmbH
# SPDX-License-Identifier: MPL-2.0

      
builds:
  - id: terramate
    binary: terramate
    main: ./cmd/terramate
    env:
      - CGO_ENABLED=0
    ldflags:
      - -extldflags "-static"
    goos:
      - linux
      - darwin
      - windows
  - id: terramate-ls
    binary: terramate-ls
    main: ./cmd/terramate-ls
    env:
      - CGO_ENABLED=0
    ldflags:
      - -extldflags "-static"
    goos:
      - linux
      - darwin
      - windows

archives:
  -
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}

    format_overrides:
      - goos: windows
        format: zip

    files: 
      - ./cosign.pub

nfpms:
  - maintainer: terramate.io 
    description: Terramate CLI is an open-source Orchestrator and Code Generator for Terraform and OpenTofu.
    homepage: https://github.com/terramate-io/terramate/
    license: MPL-2.0
    formats:
      - deb
      - rpm

furies:
  - 
    account: terramate
    secret_name: FURY_TOKEN
    formats:
      - deb
      - rpm

dockers:
  - dockerfile: hack/release/Dockerfile
    image_templates:
      - "ghcr.io/terramate-io/{{.ProjectName}}:latest"
      - "ghcr.io/terramate-io/{{.ProjectName}}:{{.Version}}"

checksum:
  name_template: 'checksums.txt'

signs:
  - cmd: cosign
    args:
      - "sign-blob"
      - "--key=env://COSIGN_PRIVATE_KEY"
      - "--output-signature=${signature}"
      - "${artifact}"
      - "--yes" # needed on cosign 2.0.0+
    artifacts: all


snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^spec:'
      - '^test:'
      - '^tests:'
      - '^testing:'
      - '^refactor:'
      - '^chore:'

release:
  prerelease: auto

  github:
    owner: terramate-io
    name: terramate

  extra_files:
    - glob: "./cosign.pub"
      # Optionally, specify the destination filename at release
      # If you omit this, it defaults to the base name of the file
      name_template: "cosign.pub"

announce:
  twitter:
    enabled: false
    message_template: |
      🥳 We just released #Terramate {{.Tag}} 🚀🚀🚀
      {{ .ReleaseURL }}

  slack:
    enabled: false
    message_template: |
      🥳 We just released #Terramate {{.Tag}} 🚀🚀🚀
      {{ .ReleaseURL }}

    channel: '#terramate'
    username: 'terramate'
    icon_emoji: ':terramate-logo:'

  discord:
    enabled: true

    message_template: |
      🥳 We just released #Terramate {{.Tag}} 🚀🚀🚀
      {{ .ReleaseURL }}

    author: 'terramate'

    # Default: 'https://goreleaser.com/static/avatar.png'
    icon_url: ''
