# Copyright 2023 Terramate GmbH
# SPDX-License-Identifier: MPL-2.0

coverage:
  status:
    project:
      default:
        target: 0%
        threshold: null
    patch:
      default:
        target: 0%
        threshold: null
