FROM golang:1.17-alpine

RUN go install github.com/mgechev/revive@latest && \
    go install golang.org/x/tools/cmd/godoc@latest && \
    go install golang.org/x/tools/cmd/cover@latest && \
    go install golang.org/x/tools/cmd/goimports@latest

RUN apk update && apk add git

WORKDIR /src
