apiVersion: terramate.io/cli/v1
kind: BundleInstance
metadata:
  name: corporate-website
  uuid: a1b2c3d4-0001-4000-8000-000000000005
spec:
  source: /bundles/catalogue/tf-aws-static-website/v1
  inputs:
    name: acme-corp-website
    domain_name: www.acme-corp.com
    additional_domains:
      - acme-corp.com
    acm_certificate_arn: arn:aws:acm:us-east-1:123456789012:certificate/abc-123
    price_class: PriceClass_All
    enable_waf: true
    index_document: index.html
    error_document: 404.html
    tags:
      project: marketing
      team: web
