// Copyright 2022 Mineiros GmbH
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package event implements a simple event stream and defines all
// events generated by different parts of Terramate.
package event

import (
	"github.com/mineiros-io/terramate/project"
	"github.com/mineiros-io/terramate/tf"
)

type (
	// VendorRequest represents an event indicating that a request to vendor was made.
	VendorRequest struct {
		// Source is the source of the module.
		Source string
		// VendorDir is where the source is supposed to be vendored.
		VendorDir project.Path
	}

	// VendorProgress represents a vendor progress event.
	VendorProgress struct {
		Message   string
		TargetDir project.Path
		Module    tf.Source
	}
)

// Stream is a stream of events.
type Stream[T any] chan T

// NewStream creates a new stream.
func NewStream[T any](buffsize int) Stream[T] {
	return Stream[T](make(chan T, buffsize))
}

// Send event on this event stream. Returns true if stream is not full,
// false if the stream is full.
func (s Stream[T]) Send(event T) bool {
	select {
	case s <- event:
		return true
	default:
		return false
	}
}
