#!/usr/bin/env bash

set -e

VERSION=$(cat VERSION)

if [[ $VERSION =~ ^[0-9]+\.[0-9]+\.[0-9]+(-[0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)?$ ]]; then
  echo "VERSION contains a valid semver: $VERSION"
else
  echo "ERROR: VERSION does not contain a valid semver: $VERSION"
  exit 1
fi
