apiVersion: terramate.io/cli/v1
kind: BundleInstance
metadata:
  name: svc-payments
  uuid: a1b2c3d4-0003-4000-8000-000000000002
spec: {}
environments:
  dev:
    source: /bundles/catalogue/tf-aws-container-service-env/v1
    inputs:
      name: payments
      container_image: 123456789012.dkr.ecr.us-east-1.amazonaws.com/acme/payments:latest
      container_port: 8080
      cpu: 256
      memory: 512
      desired_count: 1
      max_count: 2
      health_check_path: /health
      environment_variables:
        STRIPE_MODE: test
  stg:
    source: /bundles/catalogue/tf-aws-container-service-env/v1
    inputs:
      name: payments
      container_image: 123456789012.dkr.ecr.us-east-1.amazonaws.com/acme/payments:latest
      container_port: 8080
      cpu: 512
      memory: 1024
      desired_count: 2
      max_count: 4
      health_check_path: /health
      environment_variables:
        STRIPE_MODE: test
  prd:
    source: /bundles/catalogue/tf-aws-container-service-env/v1
    inputs:
      name: payments
      container_image: 123456789012.dkr.ecr.us-east-1.amazonaws.com/acme/payments:v2.7.0
      container_port: 8080
      cpu: 1024
      memory: 2048
      desired_count: 3
      max_count: 10
      health_check_path: /health
      environment_variables:
        STRIPE_MODE: live
