## This file was generated by `terrastack generate`

locals {
  # var.persons adjusted to use generated locals
  persons_map = { for p in local.ts.var.persons : p.name => p }
}

module "person" {
  # adjusted to match the local source
  source = "../../modules/terrastack-null-persons/../terraform-null-person"

  for_each = local.persons_map

  name    = each.value.name
  gender  = each.value.gender
  address = merge({city = "Berlin"}, each.value.address)
}
