## This file was generated by `terrastack generate`

locals {
  # defined by terrastack.namespace (default = "ts")
  ts = {
    var = {
      persons = [
        {
          name   = "marius"
          gender = "male"
          address = {
            street = "mein block 42"
          }
        },
        {
          name   = "elmo"
          gender = "male"
          address = {
            street = "sesamestreet 42"
            city   = "muppetvillage"
          }
        },
      ]
    }
  }
}
