## This file was generated by `terrastack generate`

module "persons" {
  source = "../../modules/terrastack-null-persons"

  persons = [
    {
      name   = "marius"
      gender = "male"
      address = {
        street = "mein block 42"
      }
    },
    {
      name   = "elmo"
      gender = "male"
      address = {
        street = "sesamestreet 42"
        city   = "muppetvillage"
      }
    },
  ]
}
