// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: plugin.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PluginService_GetPluginInfo_FullMethodName   = "/terramate.plugin.v1.PluginService/GetPluginInfo"
	PluginService_GetCapabilities_FullMethodName = "/terramate.plugin.v1.PluginService/GetCapabilities"
	PluginService_Shutdown_FullMethodName        = "/terramate.plugin.v1.PluginService/Shutdown"
)

// PluginServiceClient is the client API for PluginService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PluginServiceClient interface {
	GetPluginInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PluginInfo, error)
	GetCapabilities(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Capabilities, error)
	Shutdown(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
}

type pluginServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPluginServiceClient(cc grpc.ClientConnInterface) PluginServiceClient {
	return &pluginServiceClient{cc}
}

func (c *pluginServiceClient) GetPluginInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PluginInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PluginInfo)
	err := c.cc.Invoke(ctx, PluginService_GetPluginInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) GetCapabilities(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Capabilities, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Capabilities)
	err := c.cc.Invoke(ctx, PluginService_GetCapabilities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) Shutdown(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, PluginService_Shutdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PluginServiceServer is the server API for PluginService service.
// All implementations must embed UnimplementedPluginServiceServer
// for forward compatibility.
type PluginServiceServer interface {
	GetPluginInfo(context.Context, *Empty) (*PluginInfo, error)
	GetCapabilities(context.Context, *Empty) (*Capabilities, error)
	Shutdown(context.Context, *Empty) (*Empty, error)
	mustEmbedUnimplementedPluginServiceServer()
}

// UnimplementedPluginServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPluginServiceServer struct{}

func (UnimplementedPluginServiceServer) GetPluginInfo(context.Context, *Empty) (*PluginInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPluginInfo not implemented")
}
func (UnimplementedPluginServiceServer) GetCapabilities(context.Context, *Empty) (*Capabilities, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCapabilities not implemented")
}
func (UnimplementedPluginServiceServer) Shutdown(context.Context, *Empty) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Shutdown not implemented")
}
func (UnimplementedPluginServiceServer) mustEmbedUnimplementedPluginServiceServer() {}
func (UnimplementedPluginServiceServer) testEmbeddedByValue()                       {}

// UnsafePluginServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PluginServiceServer will
// result in compilation errors.
type UnsafePluginServiceServer interface {
	mustEmbedUnimplementedPluginServiceServer()
}

func RegisterPluginServiceServer(s grpc.ServiceRegistrar, srv PluginServiceServer) {
	// If the following call panics, it indicates UnimplementedPluginServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PluginService_ServiceDesc, srv)
}

func _PluginService_GetPluginInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).GetPluginInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_GetPluginInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).GetPluginInfo(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_GetCapabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).GetCapabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_GetCapabilities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).GetCapabilities(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_Shutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).Shutdown(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// PluginService_ServiceDesc is the grpc.ServiceDesc for PluginService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PluginService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "terramate.plugin.v1.PluginService",
	HandlerType: (*PluginServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPluginInfo",
			Handler:    _PluginService_GetPluginInfo_Handler,
		},
		{
			MethodName: "GetCapabilities",
			Handler:    _PluginService_GetCapabilities_Handler,
		},
		{
			MethodName: "Shutdown",
			Handler:    _PluginService_Shutdown_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugin.proto",
}

const (
	CommandService_GetCommands_FullMethodName             = "/terramate.plugin.v1.CommandService/GetCommands"
	CommandService_ExecuteCommand_FullMethodName          = "/terramate.plugin.v1.CommandService/ExecuteCommand"
	CommandService_ExecuteCommandWithInput_FullMethodName = "/terramate.plugin.v1.CommandService/ExecuteCommandWithInput"
)

// CommandServiceClient is the client API for CommandService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CommandServiceClient interface {
	GetCommands(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CommandList, error)
	ExecuteCommand(ctx context.Context, in *CommandRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CommandOutput], error)
	ExecuteCommandWithInput(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[CommandInput, CommandOutput], error)
}

type commandServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCommandServiceClient(cc grpc.ClientConnInterface) CommandServiceClient {
	return &commandServiceClient{cc}
}

func (c *commandServiceClient) GetCommands(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CommandList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandList)
	err := c.cc.Invoke(ctx, CommandService_GetCommands_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commandServiceClient) ExecuteCommand(ctx context.Context, in *CommandRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CommandOutput], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CommandService_ServiceDesc.Streams[0], CommandService_ExecuteCommand_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CommandRequest, CommandOutput]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CommandService_ExecuteCommandClient = grpc.ServerStreamingClient[CommandOutput]

func (c *commandServiceClient) ExecuteCommandWithInput(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[CommandInput, CommandOutput], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CommandService_ServiceDesc.Streams[1], CommandService_ExecuteCommandWithInput_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CommandInput, CommandOutput]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CommandService_ExecuteCommandWithInputClient = grpc.BidiStreamingClient[CommandInput, CommandOutput]

// CommandServiceServer is the server API for CommandService service.
// All implementations must embed UnimplementedCommandServiceServer
// for forward compatibility.
type CommandServiceServer interface {
	GetCommands(context.Context, *Empty) (*CommandList, error)
	ExecuteCommand(*CommandRequest, grpc.ServerStreamingServer[CommandOutput]) error
	ExecuteCommandWithInput(grpc.BidiStreamingServer[CommandInput, CommandOutput]) error
	mustEmbedUnimplementedCommandServiceServer()
}

// UnimplementedCommandServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCommandServiceServer struct{}

func (UnimplementedCommandServiceServer) GetCommands(context.Context, *Empty) (*CommandList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCommands not implemented")
}
func (UnimplementedCommandServiceServer) ExecuteCommand(*CommandRequest, grpc.ServerStreamingServer[CommandOutput]) error {
	return status.Error(codes.Unimplemented, "method ExecuteCommand not implemented")
}
func (UnimplementedCommandServiceServer) ExecuteCommandWithInput(grpc.BidiStreamingServer[CommandInput, CommandOutput]) error {
	return status.Error(codes.Unimplemented, "method ExecuteCommandWithInput not implemented")
}
func (UnimplementedCommandServiceServer) mustEmbedUnimplementedCommandServiceServer() {}
func (UnimplementedCommandServiceServer) testEmbeddedByValue()                        {}

// UnsafeCommandServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CommandServiceServer will
// result in compilation errors.
type UnsafeCommandServiceServer interface {
	mustEmbedUnimplementedCommandServiceServer()
}

func RegisterCommandServiceServer(s grpc.ServiceRegistrar, srv CommandServiceServer) {
	// If the following call panics, it indicates UnimplementedCommandServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CommandService_ServiceDesc, srv)
}

func _CommandService_GetCommands_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommandServiceServer).GetCommands(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommandService_GetCommands_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommandServiceServer).GetCommands(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommandService_ExecuteCommand_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CommandRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CommandServiceServer).ExecuteCommand(m, &grpc.GenericServerStream[CommandRequest, CommandOutput]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CommandService_ExecuteCommandServer = grpc.ServerStreamingServer[CommandOutput]

func _CommandService_ExecuteCommandWithInput_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CommandServiceServer).ExecuteCommandWithInput(&grpc.GenericServerStream[CommandInput, CommandOutput]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CommandService_ExecuteCommandWithInputServer = grpc.BidiStreamingServer[CommandInput, CommandOutput]

// CommandService_ServiceDesc is the grpc.ServiceDesc for CommandService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CommandService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "terramate.plugin.v1.CommandService",
	HandlerType: (*CommandServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCommands",
			Handler:    _CommandService_GetCommands_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ExecuteCommand",
			Handler:       _CommandService_ExecuteCommand_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ExecuteCommandWithInput",
			Handler:       _CommandService_ExecuteCommandWithInput_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "plugin.proto",
}

const (
	HCLSchemaService_GetHCLSchema_FullMethodName        = "/terramate.plugin.v1.HCLSchemaService/GetHCLSchema"
	HCLSchemaService_ProcessParsedBlocks_FullMethodName = "/terramate.plugin.v1.HCLSchemaService/ProcessParsedBlocks"
)

// HCLSchemaServiceClient is the client API for HCLSchemaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HCLSchemaServiceClient interface {
	GetHCLSchema(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HCLSchemaList, error)
	ProcessParsedBlocks(ctx context.Context, in *ParsedBlocksRequest, opts ...grpc.CallOption) (*ParsedBlocksResponse, error)
}

type hCLSchemaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHCLSchemaServiceClient(cc grpc.ClientConnInterface) HCLSchemaServiceClient {
	return &hCLSchemaServiceClient{cc}
}

func (c *hCLSchemaServiceClient) GetHCLSchema(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HCLSchemaList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HCLSchemaList)
	err := c.cc.Invoke(ctx, HCLSchemaService_GetHCLSchema_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hCLSchemaServiceClient) ProcessParsedBlocks(ctx context.Context, in *ParsedBlocksRequest, opts ...grpc.CallOption) (*ParsedBlocksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ParsedBlocksResponse)
	err := c.cc.Invoke(ctx, HCLSchemaService_ProcessParsedBlocks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HCLSchemaServiceServer is the server API for HCLSchemaService service.
// All implementations must embed UnimplementedHCLSchemaServiceServer
// for forward compatibility.
type HCLSchemaServiceServer interface {
	GetHCLSchema(context.Context, *Empty) (*HCLSchemaList, error)
	ProcessParsedBlocks(context.Context, *ParsedBlocksRequest) (*ParsedBlocksResponse, error)
	mustEmbedUnimplementedHCLSchemaServiceServer()
}

// UnimplementedHCLSchemaServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHCLSchemaServiceServer struct{}

func (UnimplementedHCLSchemaServiceServer) GetHCLSchema(context.Context, *Empty) (*HCLSchemaList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHCLSchema not implemented")
}
func (UnimplementedHCLSchemaServiceServer) ProcessParsedBlocks(context.Context, *ParsedBlocksRequest) (*ParsedBlocksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProcessParsedBlocks not implemented")
}
func (UnimplementedHCLSchemaServiceServer) mustEmbedUnimplementedHCLSchemaServiceServer() {}
func (UnimplementedHCLSchemaServiceServer) testEmbeddedByValue()                          {}

// UnsafeHCLSchemaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HCLSchemaServiceServer will
// result in compilation errors.
type UnsafeHCLSchemaServiceServer interface {
	mustEmbedUnimplementedHCLSchemaServiceServer()
}

func RegisterHCLSchemaServiceServer(s grpc.ServiceRegistrar, srv HCLSchemaServiceServer) {
	// If the following call panics, it indicates UnimplementedHCLSchemaServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HCLSchemaService_ServiceDesc, srv)
}

func _HCLSchemaService_GetHCLSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HCLSchemaServiceServer).GetHCLSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HCLSchemaService_GetHCLSchema_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HCLSchemaServiceServer).GetHCLSchema(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _HCLSchemaService_ProcessParsedBlocks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParsedBlocksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HCLSchemaServiceServer).ProcessParsedBlocks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HCLSchemaService_ProcessParsedBlocks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HCLSchemaServiceServer).ProcessParsedBlocks(ctx, req.(*ParsedBlocksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HCLSchemaService_ServiceDesc is the grpc.ServiceDesc for HCLSchemaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HCLSchemaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "terramate.plugin.v1.HCLSchemaService",
	HandlerType: (*HCLSchemaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetHCLSchema",
			Handler:    _HCLSchemaService_GetHCLSchema_Handler,
		},
		{
			MethodName: "ProcessParsedBlocks",
			Handler:    _HCLSchemaService_ProcessParsedBlocks_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugin.proto",
}

const (
	LifecycleService_PostInit_FullMethodName = "/terramate.plugin.v1.LifecycleService/PostInit"
)

// LifecycleServiceClient is the client API for LifecycleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LifecycleServiceClient interface {
	PostInit(ctx context.Context, in *PostInitRequest, opts ...grpc.CallOption) (*PostInitResponse, error)
}

type lifecycleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLifecycleServiceClient(cc grpc.ClientConnInterface) LifecycleServiceClient {
	return &lifecycleServiceClient{cc}
}

func (c *lifecycleServiceClient) PostInit(ctx context.Context, in *PostInitRequest, opts ...grpc.CallOption) (*PostInitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostInitResponse)
	err := c.cc.Invoke(ctx, LifecycleService_PostInit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LifecycleServiceServer is the server API for LifecycleService service.
// All implementations must embed UnimplementedLifecycleServiceServer
// for forward compatibility.
type LifecycleServiceServer interface {
	PostInit(context.Context, *PostInitRequest) (*PostInitResponse, error)
	mustEmbedUnimplementedLifecycleServiceServer()
}

// UnimplementedLifecycleServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLifecycleServiceServer struct{}

func (UnimplementedLifecycleServiceServer) PostInit(context.Context, *PostInitRequest) (*PostInitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PostInit not implemented")
}
func (UnimplementedLifecycleServiceServer) mustEmbedUnimplementedLifecycleServiceServer() {}
func (UnimplementedLifecycleServiceServer) testEmbeddedByValue()                          {}

// UnsafeLifecycleServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LifecycleServiceServer will
// result in compilation errors.
type UnsafeLifecycleServiceServer interface {
	mustEmbedUnimplementedLifecycleServiceServer()
}

func RegisterLifecycleServiceServer(s grpc.ServiceRegistrar, srv LifecycleServiceServer) {
	// If the following call panics, it indicates UnimplementedLifecycleServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LifecycleService_ServiceDesc, srv)
}

func _LifecycleService_PostInit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostInitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LifecycleServiceServer).PostInit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LifecycleService_PostInit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LifecycleServiceServer).PostInit(ctx, req.(*PostInitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LifecycleService_ServiceDesc is the grpc.ServiceDesc for LifecycleService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LifecycleService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "terramate.plugin.v1.LifecycleService",
	HandlerType: (*LifecycleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PostInit",
			Handler:    _LifecycleService_PostInit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugin.proto",
}

const (
	GenerateService_Generate_FullMethodName = "/terramate.plugin.v1.GenerateService/Generate"
)

// GenerateServiceClient is the client API for GenerateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GenerateServiceClient interface {
	Generate(ctx context.Context, in *GenerateRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GenerateOutput], error)
}

type generateServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGenerateServiceClient(cc grpc.ClientConnInterface) GenerateServiceClient {
	return &generateServiceClient{cc}
}

func (c *generateServiceClient) Generate(ctx context.Context, in *GenerateRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GenerateOutput], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GenerateService_ServiceDesc.Streams[0], GenerateService_Generate_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GenerateRequest, GenerateOutput]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GenerateService_GenerateClient = grpc.ServerStreamingClient[GenerateOutput]

// GenerateServiceServer is the server API for GenerateService service.
// All implementations must embed UnimplementedGenerateServiceServer
// for forward compatibility.
type GenerateServiceServer interface {
	Generate(*GenerateRequest, grpc.ServerStreamingServer[GenerateOutput]) error
	mustEmbedUnimplementedGenerateServiceServer()
}

// UnimplementedGenerateServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGenerateServiceServer struct{}

func (UnimplementedGenerateServiceServer) Generate(*GenerateRequest, grpc.ServerStreamingServer[GenerateOutput]) error {
	return status.Error(codes.Unimplemented, "method Generate not implemented")
}
func (UnimplementedGenerateServiceServer) mustEmbedUnimplementedGenerateServiceServer() {}
func (UnimplementedGenerateServiceServer) testEmbeddedByValue()                         {}

// UnsafeGenerateServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GenerateServiceServer will
// result in compilation errors.
type UnsafeGenerateServiceServer interface {
	mustEmbedUnimplementedGenerateServiceServer()
}

func RegisterGenerateServiceServer(s grpc.ServiceRegistrar, srv GenerateServiceServer) {
	// If the following call panics, it indicates UnimplementedGenerateServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GenerateService_ServiceDesc, srv)
}

func _GenerateService_Generate_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GenerateRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GenerateServiceServer).Generate(m, &grpc.GenericServerStream[GenerateRequest, GenerateOutput]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GenerateService_GenerateServer = grpc.ServerStreamingServer[GenerateOutput]

// GenerateService_ServiceDesc is the grpc.ServiceDesc for GenerateService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GenerateService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "terramate.plugin.v1.GenerateService",
	HandlerType: (*GenerateServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Generate",
			Handler:       _GenerateService_Generate_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "plugin.proto",
}

const (
	HostService_ReadFile_FullMethodName            = "/terramate.plugin.v1.HostService/ReadFile"
	HostService_WriteFile_FullMethodName           = "/terramate.plugin.v1.HostService/WriteFile"
	HostService_WalkDir_FullMethodName             = "/terramate.plugin.v1.HostService/WalkDir"
	HostService_GetConfigTree_FullMethodName       = "/terramate.plugin.v1.HostService/GetConfigTree"
	HostService_GetStackMetadata_FullMethodName    = "/terramate.plugin.v1.HostService/GetStackMetadata"
	HostService_SetStackMetadata_FullMethodName    = "/terramate.plugin.v1.HostService/SetStackMetadata"
	HostService_GetRootDir_FullMethodName          = "/terramate.plugin.v1.HostService/GetRootDir"
	HostService_GetUserTerramateDir_FullMethodName = "/terramate.plugin.v1.HostService/GetUserTerramateDir"
)

// HostServiceClient is the client API for HostService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HostServiceClient interface {
	ReadFile(ctx context.Context, in *ReadFileRequest, opts ...grpc.CallOption) (*ReadFileResponse, error)
	WriteFile(ctx context.Context, in *WriteFileRequest, opts ...grpc.CallOption) (*Empty, error)
	WalkDir(ctx context.Context, in *WalkDirRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DirEntry], error)
	GetConfigTree(ctx context.Context, in *GetConfigTreeRequest, opts ...grpc.CallOption) (*ConfigTreeNode, error)
	GetStackMetadata(ctx context.Context, in *GetStackRequest, opts ...grpc.CallOption) (*StackMetadata, error)
	SetStackMetadata(ctx context.Context, in *SetStackRequest, opts ...grpc.CallOption) (*Empty, error)
	GetRootDir(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StringValue, error)
	GetUserTerramateDir(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StringValue, error)
}

type hostServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHostServiceClient(cc grpc.ClientConnInterface) HostServiceClient {
	return &hostServiceClient{cc}
}

func (c *hostServiceClient) ReadFile(ctx context.Context, in *ReadFileRequest, opts ...grpc.CallOption) (*ReadFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadFileResponse)
	err := c.cc.Invoke(ctx, HostService_ReadFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServiceClient) WriteFile(ctx context.Context, in *WriteFileRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, HostService_WriteFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServiceClient) WalkDir(ctx context.Context, in *WalkDirRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DirEntry], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &HostService_ServiceDesc.Streams[0], HostService_WalkDir_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WalkDirRequest, DirEntry]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HostService_WalkDirClient = grpc.ServerStreamingClient[DirEntry]

func (c *hostServiceClient) GetConfigTree(ctx context.Context, in *GetConfigTreeRequest, opts ...grpc.CallOption) (*ConfigTreeNode, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigTreeNode)
	err := c.cc.Invoke(ctx, HostService_GetConfigTree_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServiceClient) GetStackMetadata(ctx context.Context, in *GetStackRequest, opts ...grpc.CallOption) (*StackMetadata, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StackMetadata)
	err := c.cc.Invoke(ctx, HostService_GetStackMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServiceClient) SetStackMetadata(ctx context.Context, in *SetStackRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, HostService_SetStackMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServiceClient) GetRootDir(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StringValue, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StringValue)
	err := c.cc.Invoke(ctx, HostService_GetRootDir_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServiceClient) GetUserTerramateDir(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StringValue, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StringValue)
	err := c.cc.Invoke(ctx, HostService_GetUserTerramateDir_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HostServiceServer is the server API for HostService service.
// All implementations must embed UnimplementedHostServiceServer
// for forward compatibility.
type HostServiceServer interface {
	ReadFile(context.Context, *ReadFileRequest) (*ReadFileResponse, error)
	WriteFile(context.Context, *WriteFileRequest) (*Empty, error)
	WalkDir(*WalkDirRequest, grpc.ServerStreamingServer[DirEntry]) error
	GetConfigTree(context.Context, *GetConfigTreeRequest) (*ConfigTreeNode, error)
	GetStackMetadata(context.Context, *GetStackRequest) (*StackMetadata, error)
	SetStackMetadata(context.Context, *SetStackRequest) (*Empty, error)
	GetRootDir(context.Context, *Empty) (*StringValue, error)
	GetUserTerramateDir(context.Context, *Empty) (*StringValue, error)
	mustEmbedUnimplementedHostServiceServer()
}

// UnimplementedHostServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHostServiceServer struct{}

func (UnimplementedHostServiceServer) ReadFile(context.Context, *ReadFileRequest) (*ReadFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadFile not implemented")
}
func (UnimplementedHostServiceServer) WriteFile(context.Context, *WriteFileRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method WriteFile not implemented")
}
func (UnimplementedHostServiceServer) WalkDir(*WalkDirRequest, grpc.ServerStreamingServer[DirEntry]) error {
	return status.Error(codes.Unimplemented, "method WalkDir not implemented")
}
func (UnimplementedHostServiceServer) GetConfigTree(context.Context, *GetConfigTreeRequest) (*ConfigTreeNode, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConfigTree not implemented")
}
func (UnimplementedHostServiceServer) GetStackMetadata(context.Context, *GetStackRequest) (*StackMetadata, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStackMetadata not implemented")
}
func (UnimplementedHostServiceServer) SetStackMetadata(context.Context, *SetStackRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SetStackMetadata not implemented")
}
func (UnimplementedHostServiceServer) GetRootDir(context.Context, *Empty) (*StringValue, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRootDir not implemented")
}
func (UnimplementedHostServiceServer) GetUserTerramateDir(context.Context, *Empty) (*StringValue, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserTerramateDir not implemented")
}
func (UnimplementedHostServiceServer) mustEmbedUnimplementedHostServiceServer() {}
func (UnimplementedHostServiceServer) testEmbeddedByValue()                     {}

// UnsafeHostServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HostServiceServer will
// result in compilation errors.
type UnsafeHostServiceServer interface {
	mustEmbedUnimplementedHostServiceServer()
}

func RegisterHostServiceServer(s grpc.ServiceRegistrar, srv HostServiceServer) {
	// If the following call panics, it indicates UnimplementedHostServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HostService_ServiceDesc, srv)
}

func _HostService_ReadFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).ReadFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostService_ReadFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).ReadFile(ctx, req.(*ReadFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostService_WriteFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).WriteFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostService_WriteFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).WriteFile(ctx, req.(*WriteFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostService_WalkDir_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WalkDirRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(HostServiceServer).WalkDir(m, &grpc.GenericServerStream[WalkDirRequest, DirEntry]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HostService_WalkDirServer = grpc.ServerStreamingServer[DirEntry]

func _HostService_GetConfigTree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfigTreeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).GetConfigTree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostService_GetConfigTree_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).GetConfigTree(ctx, req.(*GetConfigTreeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostService_GetStackMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).GetStackMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostService_GetStackMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).GetStackMetadata(ctx, req.(*GetStackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostService_SetStackMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetStackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).SetStackMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostService_SetStackMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).SetStackMetadata(ctx, req.(*SetStackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostService_GetRootDir_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).GetRootDir(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostService_GetRootDir_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).GetRootDir(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostService_GetUserTerramateDir_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).GetUserTerramateDir(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostService_GetUserTerramateDir_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).GetUserTerramateDir(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// HostService_ServiceDesc is the grpc.ServiceDesc for HostService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HostService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "terramate.plugin.v1.HostService",
	HandlerType: (*HostServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReadFile",
			Handler:    _HostService_ReadFile_Handler,
		},
		{
			MethodName: "WriteFile",
			Handler:    _HostService_WriteFile_Handler,
		},
		{
			MethodName: "GetConfigTree",
			Handler:    _HostService_GetConfigTree_Handler,
		},
		{
			MethodName: "GetStackMetadata",
			Handler:    _HostService_GetStackMetadata_Handler,
		},
		{
			MethodName: "SetStackMetadata",
			Handler:    _HostService_SetStackMetadata_Handler,
		},
		{
			MethodName: "GetRootDir",
			Handler:    _HostService_GetRootDir_Handler,
		},
		{
			MethodName: "GetUserTerramateDir",
			Handler:    _HostService_GetUserTerramateDir_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WalkDir",
			Handler:       _HostService_WalkDir_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "plugin.proto",
}
