// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

package sandbox_test

import (
	"testing"

	"github.com/rs/zerolog"
	"github.com/terramate-io/terramate/test"
	"github.com/terramate-io/terramate/test/sandbox"
)

func init() {
	zerolog.SetGlobalLevel(zerolog.Disabled)
}

func TestInitializedGitHasOriginMain(t *testing.T) {
	basedir := t.TempDir()
	git := sandbox.NewGit(t, basedir)
	git.Init()
	git.RevParse("origin/main")
}

func TestInitializeArbitraryRemote(t *testing.T) {
	basedir := t.TempDir()
	git := sandbox.NewGit(t, basedir)
	git.InitLocalRepo()

	// the main branch only exists after first commit.
	path := test.WriteFile(t, git.BaseDir(), "README.md", "# generated by terramate")
	git.Add(path)
	git.Commit("first commit")

	const remote = "mineiros"
	const remoteBranch = "default"

	git.SetupRemote(remote, remoteBranch, "main")
	git.RevParse(remote + "/" + remoteBranch)
}
