// Copyright 2026 Terramate GmbH
// SPDX-License-Identifier: MPL-2.0

// Code generated by goyacc -o parser.go parser.y. DO NOT EDIT.

//line parser.y:2
package typeschema

import (
	"fmt"
	__yyfmt__ "fmt"
	"strings"
	"text/scanner"
)

//line parser.y:2

//line parser.y:12
type yySymType struct {
	yys  int
	str  string
	typ  Type
	list []Type
}

const KW_LIST = 57346
const KW_SET = 57347
const KW_MAP = 57348
const KW_TUPLE = 57349
const KW_OBJECT = 57350
const KW_ANY = 57351
const KW_STRING = 57352
const KW_BOOL = 57353
const KW_NUMBER = 57354
const KW_ANY_OF = 57355
const KW_HAS = 57356
const STR = 57357

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"KW_LIST",
	"KW_SET",
	"KW_MAP",
	"KW_TUPLE",
	"KW_OBJECT",
	"KW_ANY",
	"KW_STRING",
	"KW_BOOL",
	"KW_NUMBER",
	"KW_ANY_OF",
	"KW_HAS",
	"STR",
	"'('",
	"')'",
	"','",
	"'.'",
	"'+'",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line parser.y:138

type Lexer struct {
	Scanner scanner.Scanner
	Result  Type
	Err     error
}

func NewLexer(input string) *Lexer {
	l := &Lexer{}
	l.Scanner.Init(strings.NewReader(input))
	l.Scanner.Mode = scanner.ScanIdents | scanner.ScanStrings | scanner.ScanInts
	return l
}

func (l *Lexer) Lex(lval *yySymType) int {
	token := l.Scanner.Scan()
	text := l.Scanner.TokenText()

	if l.Err != nil {
		return 0
	}

	switch token {
	case scanner.EOF:
		return 0
	case scanner.Ident:
		switch text {
		// Core Keywords
		case "list":
			return KW_LIST
		case "set":
			return KW_SET
		case "map":
			return KW_MAP
		case "tuple":
			return KW_TUPLE
		case "object":
			return KW_OBJECT
		case "any":
			return KW_ANY
		case "string":
			return KW_STRING
		case "bool":
			return KW_BOOL
		case "number":
			return KW_NUMBER
		case "any_of":
			return KW_ANY_OF
		case "has":
			return KW_HAS

		default:
			lval.str = text
			return STR
		}
	default:
		return int(text[0])
	}
}

func (l *Lexer) Error(s string) {
	l.Err = fmt.Errorf("%s at position %s", s, l.Scanner.Pos())
}

//line yacctab:1
var yyExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 5,
	20, 17,
	-2, 4,
	-1, 6,
	20, 16,
	-2, 5,
	-1, 46,
	20, 16,
	-2, 19,
}

const yyPrivate = 57344

const yyLast = 60

var yyAct = [...]int8{
	42, 2, 41, 12, 25, 6, 32, 23, 18, 19,
	20, 21, 5, 4, 14, 15, 16, 22, 24, 17,
	57, 52, 51, 52, 54, 26, 53, 50, 38, 39,
	40, 35, 43, 34, 49, 48, 36, 47, 35, 46,
	44, 33, 31, 17, 1, 30, 29, 28, 27, 37,
	45, 13, 11, 55, 10, 9, 56, 8, 7, 3,
}

var yyPact = [...]int16{
	4, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -16, -1000, -1000, -1000, -1000, 6, 32, 31,
	30, 29, 26, -14, 25, 28, 34, 4, 4, 4,
	4, 4, 28, 28, -1000, -1000, -1000, -1000, 18, 17,
	10, 5, -1000, 8, -1000, 7, -1000, -16, -1000, -1000,
	-1000, -1000, 4, 4, -1000, -1000, 3, -1000,
}

var yyPgo = [...]int8{
	0, 0, 59, 58, 57, 55, 54, 52, 3, 51,
	50, 7, 5, 2, 44,
}

var yyR1 = [...]int8{
	0, 14, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 7, 8, 8, 11, 11, 9, 10,
	10, 2, 2, 2, 3, 4, 5, 6, 13, 13,
	12, 12,
}

var yyR2 = [...]int8{
	0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 6, 3, 3, 1, 1, 4, 1,
	1, 1, 1, 1, 4, 4, 4, 4, 3, 1,
	1, 3,
}

var yyChk = [...]int16{
	-1000, -14, -1, -2, 9, 8, -12, -3, -4, -5,
	-6, -7, -8, -9, 10, 11, 12, 15, 4, 5,
	6, 7, 13, -11, 14, 20, 19, 16, 16, 16,
	16, 16, 20, 16, -11, -12, 8, 15, -1, -1,
	-1, -13, -1, -1, -11, -10, -12, -8, 17, 17,
	17, 17, 18, 18, 17, -1, -13, 17,
}

var yyDef = [...]int8{
	0, -2, 1, 2, 3, -2, -2, 6, 7, 8,
	9, 10, 11, 12, 21, 22, 23, 30, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 15, 16, 17, 31, 0, 0,
	0, 0, 29, 0, 14, 0, -2, 20, 24, 25,
	26, 27, 0, 0, 18, 28, 0, 13,
}

var yyTok1 = [...]int8{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	16, 17, 3, 20, 18, 3, 19,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:46
		{
			yylex.(*Lexer).Result = yyDollar[1].typ
		}
	case 3:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:52
		{
			yyVAL.typ = &AnyType{}
		}
	case 4:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:53
		{
			yyVAL.typ = &ObjectType{}
		}
	case 5:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:54
		{
			yyVAL.typ = &ReferenceType{Name: yyDollar[1].str}
		}
	case 13:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser.y:64
		{
			yyVAL.typ = &VariantType{
				Options: append([]Type{yyDollar[3].typ}, yyDollar[5].list...),
			}
		}
	case 14:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:71
		{
			yyVAL.typ = &MergedObjectType{
				Objects: []Type{yyDollar[1].typ, yyDollar[3].typ},
			}
		}
	case 15:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:76
		{
			merged := yyDollar[1].typ.(*MergedObjectType)
			yyVAL.typ = &MergedObjectType{
				Objects: append(merged.Objects, yyDollar[3].typ),
			}
		}
	case 16:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:84
		{
			yyVAL.typ = &ReferenceType{Name: yyDollar[1].str}
		}
	case 17:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:85
		{
			yyVAL.typ = &ObjectType{}
		}
	case 18:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:88
		{
			yyVAL.typ = &NonStrictType{Inner: yyDollar[3].typ}
		}
	case 19:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:93
		{
			yyVAL.typ = &ReferenceType{Name: yyDollar[1].str}
		}
	case 21:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:99
		{
			yyVAL.typ = &PrimitiveType{Name: "string"}
		}
	case 22:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:100
		{
			yyVAL.typ = &PrimitiveType{Name: "bool"}
		}
	case 23:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:101
		{
			yyVAL.typ = &PrimitiveType{Name: "number"}
		}
	case 24:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:104
		{
			yyVAL.typ = &ListType{ValueType: yyDollar[3].typ}
		}
	case 25:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:109
		{
			yyVAL.typ = &SetType{ValueType: yyDollar[3].typ}
		}
	case 26:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:114
		{
			yyVAL.typ = &MapType{ValueType: yyDollar[3].typ}
		}
	case 27:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:119
		{
			yyVAL.typ = &TupleType{Elems: yyDollar[3].list}
		}
	case 28:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:125
		{
			yyVAL.list = append(yyDollar[1].list, yyDollar[3].typ)
		}
	case 29:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:128
		{
			yyVAL.list = []Type{yyDollar[1].typ}
		}
	case 31:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:134
		{
			yyVAL.str = yyDollar[1].str + "." + yyDollar[3].str
		}
	}
	goto yystack /* stack new state and value */
}
